export const SET_BOARD = 'SET_BOARD'
export const SET_BOARD_LOADING = 'SET_BOARD_LOADING'
export const SET_INPUT = 'SET_INPUT'
export const SET_BOARD_ERROR = 'SET_BOARD_ERROR'
export const SET_DIFFICULTY_LEVEL = 'SET_DIFFICULTY_LEVEL'

export const SET_STATUS = 'SET_STATUS'

export const SET_PLAYER = 'SET_PLAYER'
export const ADD_PLAYER_LIST = 'ADD_PLAYER_LIST'